apiVersion: v1
data:
  DB_DATABASE: lradb
  DB_HOST: lradb.vpc.internal
  DB_PORT: "3306"
  DB_TYPE: mysql
  GRPC_CL_GEOCODING_HOST: be-ap-svc.app-a.svc.cluster.local
  GRPC_CL_GEOCODING_PAKAGE: rpc
  GRPC_CL_GEOCODING_PORT: "9011"
  GRPC_CL_GEOCODING_PROTOS: geocoding.proto
  GRPC_CL_RESTAURANTS_HOST: be-ap-svc.app-a.svc.cluster.local
  GRPC_CL_RESTAURANTS_PAKAGE: rpc
  GRPC_CL_RESTAURANTS_PORT: "9011"
  GRPC_CL_RESTAURANTS_PROTOS: restaurants.proto
  GRPC_CL_USERS_HOST: be-ap-svc.app-a.svc.cluster.local
  GRPC_CL_USERS_PAKAGE: rpc
  GRPC_CL_USERS_PORT: "9011"
  GRPC_CL_USERS_PROTOS: users.proto
  HTTP_MAX_REDIRECTS: "5"
  HTTP_SV_PORT: "9001"
  HTTP_TIMEOUT: "5000"
  JWT_EXPIRES_IN: "3600"
  NODE_ENV: production
  REDIS_HOST: cache-svc.ext-a.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_TTL: "1000"
kind: ConfigMap
metadata:
  name: bff-ap-config
  namespace: app-a
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bff-ap-svc
  name: bff-ap-svc
  namespace: app-a
spec:
  ports:
  - name: bff-ap-port
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: bff-ap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-ap
  namespace: app-a
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: bff-ap
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bff-ap
      name: bff-ap
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: bff-ap-config
        - secretRef:
            name: bff-ap-secret
        image: t3goto/bff-ap:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls
            - /usr/local/bin/node
          failureThreshold: 10
          initialDelaySeconds: 0
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: bff-ap
        ports:
        - containerPort: 9001
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/v1/health/readiness
            port: 9001
          initialDelaySeconds: 0
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 150m
            memory: 150Mi
          requests:
            cpu: 10m
            memory: 10Mi
        startupProbe:
          failureThreshold: 100
          httpGet:
            path: /api/v1/health/readiness
            port: 9001
          initialDelaySeconds: 0
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bff-ap-secret
  namespace: app-a
spec:
  encryptedData:
    DB_PASSWORD: AgA6fAPRuOjNmOveDGohfOaeAItgfNBQltJ59Zhxfqkuo5bS5xmN8mf98y9oSe/YrruVwB1iKLcFPFIFiQ3YGcFTOl9AXjf+7zsMA3pVWBFWT8BJ3Tfw2Ob1GXByOxfyx/mEVm+pQdztExMOQVs+6zaBFWxZmjK2bhSo8NU9tP+zCReUAIiogXyT+YHFTMuS6/tVlUggW7BPPiSTM1de1T6Dyso3V02VmUYyoK9DmnZlAolnuYFMPC8SrcLo0sT8+VUI6Ty1CYLSXqFngD+i1eUhChrW3OAatuTtKx3t8WVqF5eiqh+2AMTlC/Ymz08/8nteHmqLNzNbMTZ5RlwChXvz2JAFxxGnD+yvdlr/Ke2XNrxdLih/aV8dj+z+EB+qEzru8yzTTnAGy11wy5TIleMG94O5N2QJgRji4K+lkkgqQEut7J4URv07PC1AYkhO7rl7PxjoIQYD2EoQ6eXgW/oxWV8Wm9WrAHIlvNz9jevUeK2jTSnVzzuvebrw5Z5RwBsjVMmgL1O1mT/opAYK5WoNaxLAU1Pqk+H5JQg3BNSyBv+soyqP/sg6hiIQzhoO0lrcW98rHwDsaFd1X2KxKfsEsWDbNjD8sQ2NMGKTNnwg2ka+J13JlEiPo81plg6g3uarPFM76N+FHiKAnn3lg/OXpbkJzYXCS2AnoLrQERlLyWon3cBUq7u9A0UuCCOY56ixytxl3dPC7Q==
    DB_USERNAME: AgAXXtBqQ/ObRC39NzrYWt6Kdre7zSJVMtvAn0hcBNNMvOlXWjBm8qu240+P0bD7tqiUdHkUmxcd8jjKCim0/4mfoDOu1+j6ohHPYxvCK8YIkaWxcVQVlola0pJuJHXBFVD9MbxubpC8F6AMigK4YVRelvMR9i+ho0Me1NmQhAGSL+c5THdpnqi9aM4ZoCUYpenduQBlOMFPSFYsXyb7xuF2VxZfBJPA5f5yEBw7IvGO+TSyA8nZgWX99dUS0swdpNtWIAkAQ0ELGenLZOKTwDngedgMYNmHbTTjfUmRBSk+oVsXFIl/BkjzeAFMr1fxQtOagoFTB+0xzAxwA5JM4Jar/kXA+iEPJ0wlg+c/bAacuRGqbZARDnB1pMF6FI5hSg+0N8lVY5LSZpNF7K3Z6l+YO/JHR73jieIiZeXN6nOL3IIBpYamB5bzVK+wi5kd1PS7xiHCHp1NyMABIpSiz5ERRm7HO+Sbbg8FmMDrF1xCgEJkcDRKgAU8LeV7l/ISrqxvbRYzcIcc+YXH6rPI0K36rlviGpnQuF4tViBP8v5IohWeU3pFe+ZpwXeFP1/Hm9BSrtNrI/MzB6B/M5GlvhLhcYIUanVk2M0xTFQO7rlcEeYYW8rYXXNdeQXzS+pCHiO4xLgESvtXfa0vBvNUbQ8d8kUu4cVLn1t0pLHs1BPHsEqbj0ZS9rHBTIVvyrt3/qQEWBSkSA==
    JWT_SECRET: AgBDA7JGHHqtUsUGCb2+1IYaBJMINgCLlkyWBSM7cvwLUmQOV6C+KReQo24r8raKM+ZrCCBNDyTdqz/oQH5X4Mu2Ie1k+G6iBw3uTAADk9PveRfu0AtUOKKtPjxKbM4/T07H/kh8FP+3+MWtkESHrNxtmRf3Gil5YnyFbgLGzpJ/liH4TX8hBcFSgU22gSIdBi+3j2DwyMeZM8EMZBHc2hz/GVcXkcvCOF7yYkWUdcDu8FWu6VABK8Li950DEdjfG1ulHTHv158DqNWZDkhaRu+/1QRYb597YDjis0C3ojzU3+FqPqiupbmGOpnK6pgwKaHn/kYtpmJhuVKj7lxBlxnmk1uiaDJ7tnD/cQ/4xDehfk8iRoyArdugDU2PdOqD+NC0IKpnzMv7TnYcDgeRmgBfF+Vq5mU99RC5B5u/RMWFMjnjnv1J7JDxw9J3lSzySkRnorEhQjQsJbcrx7jlmFrx3ARsvx4ebFmjL7vz/C3v8N3V21afvtwUjEHuI3/t4gYKlEiXlO9Mb9Ku90kFLW1gq7+Wd2PS0+LZagtq4U3UQPOFa8R2kTzqG1CqYY9NWdrTe383H5KXixyqM0OZUuWI8RKTeAmQBkqiVTWsN1UjlZuCLT8Prxvu4xmcscyy9vkarrV3EI5w3z3pzqww/8OehXquEfK+JPL9uVmHID+xSowCrANQY9Eq0s3kxxxro1y34v+0cYs4KLaTQJTfmqmx
  template:
    metadata:
      creationTimestamp: null
      name: bff-ap-secret
      namespace: app-a
    type: Opaque
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: bff-ap-dr
  namespace: app-a
spec:
  host: bff-ap-svc.app-a.svc.cluster.local
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bff-ap-vs-gw
  namespace: app-a
spec:
  gateways:
  - istio-system/ingress-gateway
  hosts:
  - www.lratg.com
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: bff-ap-svc.app-a.svc.cluster.local
        port:
          number: 9001
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bff-ap-vs-mesh
  namespace: app-a
spec:
  hosts:
  - bff-ap-svc.app-a.svc.cluster.local
  http:
  - route:
    - destination:
        host: bff-ap-svc.app-a.svc.cluster.local
        port:
          number: 9001
