#################################
# Kustomization (overlays)
#################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/app/overlays/dev
- ../../base/ext/overlays/dev
- ../../base/istio/overlays/dev
# - ../../base/sys/overlays/dev
- ../../base/vendor/overlays/dev

