#################################
# Kustomization (overlays)
#################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/app/overlays/prod
- ../../base/ext/overlays/prod
- ../../base/istio/overlays/prod
# - ../../base/sys/overlays/prod
- ../../base/vendor/overlays/prod

