apiVersion: v1
data:
  CONTENTS_SOURCE_BRANCH: develop
  CONTENTS_SOURCE_DIR: apl/fe/dist
  CONTENTS_SOURCE_URL: https://github.com/t3-goto/lra-app
kind: ConfigMap
metadata:
  name: fe-contents-cloner-config
  namespace: app-a
---
apiVersion: v1
data:
  config.json: |
    {
      "BFF_BASE_URL": "https://www.lratg.com/api/v1"
    }
  default.conf: |
    # vertual server (default)
    server {
      listen 8001 default;
      listen [::]:8001;
      server_name localhost;

      # root
      root /usr/share/nginx/html;
      index index.html index.htm;

      # location (static)
      location / {
        try_files $uri $uri/ =404;
      }

      # error page
      error_page 500 502 503 504 /50x.html;
      location = /50x.html {
        root /usr/share/nginx/html;
      }
    }
  nginx.conf: |
    # uesr
    user nginx;

    # worker
    worker_processes auto;
    worker_rlimit_nofile 100000;

    # pid
    pid /var/run/nginx.pid;

    # events
    events {
        worker_connections 2048;
        multi_accept on;
        use epoll;
    }

    # http server
    http {
      # security (server info)
      server_tokens off;

      # security (connection)
      limit_conn_zone $binary_remote_addr zone=addr:5m;
      limit_conn addr 100;

      # performance
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;

      # performance (timeout)
      keepalive_timeout 10;
      client_header_timeout 10;
      client_body_timeout 10;
      reset_timedout_connection on;
      send_timeout 10;

      # performance (open_file_cache)
      open_file_cache max=100000 inactive=20s;
      open_file_cache_valid 30s;
      open_file_cache_min_uses 2;
      open_file_cache_errors on;

      # performance (compression)
      gzip on;
      gzip_static on;
      gzip_http_version 1.0;
      gzip_disable "msie6";
      gzip_proxied any;
      gzip_min_length 1024;
      gzip_comp_level 6;
      gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;


      # proxy headers
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # log
      log_not_found on;
      error_log /var/log/nginx/error.log error;
      log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                                '$status $body_bytes_sent "$http_referer" '
                                '"$http_user_agent" "$http_x_forwarded_for"';
      access_log /var/log/nginx/access.log main;

      # cache (no cache)
      expires epoch;

      # mime types
      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      # virtual server
      include /etc/nginx/conf.d/*.conf;
    }
kind: ConfigMap
metadata:
  name: fe-web-config
  namespace: app-a
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fe-web-svc
  name: fe-web-svc
  namespace: app-a
spec:
  ports:
  - name: fe-web-port
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: fe-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-web
  namespace: app-a
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: fe-web
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fe-web
      name: fe-web
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: fe-web-config
        image: t3goto/fe-web:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls
            - /usr/share/nginx/html/50x.html
          failureThreshold: 10
          initialDelaySeconds: 0
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: fe-web
        ports:
        - containerPort: 8001
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /index.html
            port: 8001
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 150m
            memory: 150Mi
          requests:
            cpu: 10m
            memory: 10Mi
        startupProbe:
          failureThreshold: 100
          httpGet:
            path: /index.html
            port: 8001
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf-vol
          readOnly: true
          subPath: nginx.conf
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginx-conf-default-vol
          readOnly: true
          subPath: default.conf
        - mountPath: /usr/share/nginx/html/config.json
          name: contents-config-vol
          readOnly: true
          subPath: config.json
      volumes:
      - configMap:
          items:
          - key: nginx.conf
            path: nginx.conf
          name: fe-web-config
        name: nginx-conf-vol
      - configMap:
          items:
          - key: default.conf
            path: default.conf
          name: fe-web-config
        name: nginx-conf-default-vol
      - configMap:
          items:
          - key: config.json
            path: config.json
          name: fe-web-config
        name: contents-config-vol
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: fe-web-dr
  namespace: app-a
spec:
  host: fe-web-svc.app-a.svc.cluster.local
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: fe-web-vs-gw
  namespace: app-a
spec:
  gateways:
  - istio-system/ingress-gateway
  hosts:
  - www.lratg.com
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: fe-web-svc.app-a.svc.cluster.local
        port:
          number: 8001
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: fe-web-vs-mesh
  namespace: app-a
spec:
  hosts:
  - fe-web-svc.app-a.svc.cluster.local
  http:
  - route:
    - destination:
        host: fe-web-svc.app-a.svc.cluster.local
        port:
          number: 8001
