################################
# Ingress (Istio)
#################################
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: dummy
spec:
  selector:
    istio: ingressgateway
  servers:
  # - port:
  #     number: 80
  #     name: http
  #     protocol: HTTP
  #   tls:
  #     httpsRedirect: true
  #   hosts:
  #   - dummy
  # - port:
  #     number: 443
  #     name: https
  #     protocol: HTTPS
  #   tls:
  #     mode: SIMPLE
  #     credentialName: ingress-gateway-credential
  #   hosts:
  #   - dummy
