#################################
# IstioOperator (default)
#################################
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: dummy
  name: istiocontrolplane
spec:
  profile: default
