#################################
# ClusterRole (Nodes)
#################################
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodes
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","delete"]
---
#################################
# ClusterRoleBinding (Nodes to Liberator)
#################################
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nodes
subjects:
- kind: ServiceAccount
  name: liberator
  namespace: dummy
roleRef:
  kind: ClusterRole
  name: nodes
  apiGroup: rbac.authorization.k8s.io
