#################################
# LimitRange (system)
#################################
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: dummy
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 200Mi
      defaultRequest:
        cpu: 100m
        memory: 100Mi
