#################################
# LimitRange（application）
#################################
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: dummy
spec:
  limits:
    - type: Container
      default:
        cpu: 150m
        memory: 150Mi
      defaultRequest:
        cpu: 10m
        memory: 10Mi
