version: 2.1
# orbs:
#   slack: circleci/slack@4.2.1
commands:
  sparse-checkout:
    description: 'Sparse checkout for sub directories.'
    steps:
    - run:
        name: Sparse Checkout
        command: |
          git init
          git config core.sparsecheckout true
          git remote add origin ${SOURCE_REPO}.git
          echo ${SOURCE_DIR} >.git/info/sparse-checkout
          git pull origin ${SOURCE_BRANCH}
jobs:
  install_deps:
    docker:
    - image: cimg/node:12.20
    environment:
      SOURCE_REPO: https://github.com/t3-goto/lra-app
      SOURCE_BRANCH: develop
      SOURCE_DIR: apl/fe
    steps:
    - sparse-checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "apl/fe/yarn.lock"}}
        - v1-dependencies-
    - run:
        name: Yarn Install
        command: cd ${SOURCE_DIR} && yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "apl/fe/yarn.lock"}}
    - persist_to_workspace:
        root: ~/project/apl/fe
        paths:
        - node_modules/*

    # - slack/notify:
    #     event: fail
    #     template: basic_fail_1
    # - slack/notify:
    #     event: pass
    #     template: success_tagged_deploy_1
workflows:
  build_and_deploy:
    jobs:
    - install_deps
        # context: SLACK_INTEGRATION
