version: 2.1
orbs:
  slack: circleci/slack@4.2.1

executors:
  fe_default:
    working_directory: ~/project/apl/fe
    docker:
    - image: cimg/node:12.20
    environment:
      SYSTEM: fe-web
      SOURCE_REPO: https://github.com/t3-goto/lra-app
      SOURCE_BRANCH: feature/mod-circleci
      SOURCE_DIR: apl/fe

  bff_default:
    working_directory: ~/project/apl/bff
    docker:
    - image: cimg/node:12.20
    environment:
      SYSTEM: bff-ap
      SOURCE_REPO: https://github.com/t3-goto/lra-app
      SOURCE_BRANCH: feature/mod-circleci
      SOURCE_DIR: apl/bff

  be_default:
    working_directory: ~/project/apl/be
    docker:
    - image: cimg/node:12.20
    environment:
      SYSTEM: be-ap
      SOURCE_REPO: https://github.com/t3-goto/lra-app
      SOURCE_BRANCH: feature/mod-circleci
      SOURCE_DIR: apl/be

commands:
  sparse_checkout:
    description: 'Sparse checkout for sub directories.'
    steps:
    - run:
        name: Sparse checkout
        command: |
          cd ~/project
          git init
          git config core.sparsecheckout true
          git remote add origin ${SOURCE_REPO}.git
          echo ${SOURCE_DIR} >.git/info/sparse-checkout
          git pull origin ${SOURCE_BRANCH}

  # install_deps:
  #   description: 'Install dependencies.'
  #   parameters:
  #     system:
  #       type: enum
  #       enum: ["fe-web", "be-ffp", "be-ap"]
  #   steps:
  #   - when:
  #       condition:
  #         equal: [<< parameter.system >>, "fe-web"]
  #       steps:
  #       - restore_cache:
  #           keys:
  #           - v1-dependencies-fe-web-{{ .Branch }}-{{ checksum "yarn.lock"}}
  #           - v1-dependencies-fe-web-{{ .Branch }}
  #           - v1-dependencies-fe-web-
  #       - run:
  #           name: Yarn install
  #           command: yarn install
  #       - save_cache:
  #           paths:
  #           - node_modules
  #           key: v1-dependencies-fe-web-{{ checksum "yarn.lock"}}
  #       - persist_to_workspace:
  #           root: ./
  #           paths:
  #           - node_modules/*
  #   - when:
  #       condition:
  #         equal: [<< parameter.system >>, "bff-ap"]
  #       steps:
  #       - restore_cache:
  #           keys:
  #           - v1-dependencies-bff-ap-{{ .Branch }}-{{ checksum "yarn.lock"}}
  #           - v1-dependencies-bff-ap-{{ .Branch }}
  #           - v1-dependencies-bff-ap-
  #       - run:
  #           name: Yarn install
  #           command: yarn install
  #       - save_cache:
  #           paths:
  #           - node_modules
  #           key: v1-dependencies-bff-ap-{{ checksum "yarn.lock"}}
  #       - persist_to_workspace:
  #           root: ./
  #           paths:
  #           - node_modules/*
  #   - when:
  #       condition:
  #         equal: [<< parameter.system >>, "be-ap"]
  #       steps:
  #       - restore_cache:
  #           keys:
  #           - v1-dependencies-be-ap-{{ .Branch }}-{{ checksum "yarn.lock"}}
  #           - v1-dependencies-be-ap-{{ .Branch }}
  #           - v1-dependencies-be-ap-
  #       - run:
  #           name: Yarn install
  #           command: yarn install
  #       - save_cache:
  #           paths:
  #           - node_modules
  #           key: v1-dependencies-be-ap-{{ checksum "yarn.lock"}}
  #       - persist_to_workspace:
  #           root: ./
  #           paths:
  #           - node_modules/*

  fe_install_deps:
    description: 'Install dependencies for fe-web.'
    steps:
    - restore_cache:
        keys:
        # - v1-dependencies-fe-web-{{ .Branch }}-{{ checksum "yarn.lock"}}
        # - v1-dependencies-fe-web-{{ .Branch }}
        - v1-dependencies-fe-web-{{ .Branch }}-{{ checksum "yarn.lock"}}
        - v1-dependencies-fe-web-
    - run:
        name: Yarn install
        command: yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-fe-web-{{ .Branch }}-{{ checksum "yarn.lock"}}
    - persist_to_workspace:
        root: ./
        paths:
        - node_modules/*

  bff_install_deps:
    description: 'Install dependencies for bff-ap.'
    steps:
    - restore_cache:
        keys:
        - v1-dependencies-bff-ap-{{ .Branch }}-{{ checksum "yarn.lock"}}
        - v1-dependencies-bff-ap-{{ .Branch }}
        - v1-dependencies-bff-ap-
    - run:
        name: Yarn install
        command: yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-bff-ap-{{ .Branch }}-{{ checksum "yarn.lock"}}
    - persist_to_workspace:
        root: ./
        paths:
        - node_modules/*

  be_install_deps:
    description: 'Install dependencies for be-ap.'
    steps:
    - restore_cache:
        keys:
        - v1-dependencies-be-ap-{{ .Branch }}-{{ checksum "yarn.lock"}}
        - v1-dependencies-be-ap-{{ .Branch }}
        - v1-dependencies-be-ap-
    - run:
        name: Yarn install
        command: yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-be-ap-{{ .Branch }}-{{ checksum "yarn.lock"}}
    - persist_to_workspace:
        root: ./
        paths:
        - node_modules/*

  eslint:
    description: 'Eslint.'
    steps:
    - attach_workspace:
        at: ./
    - run:
        name: Make report directory
        command: mkdir reports
    - run:
        name: Lint
        command: npx eslint ./src --ext .ts,tsx --format junit --output-file ./reports/eslint/eslint.xml
    - store_test_results:
        path: reports
    - store_artifacts:
        path: reports

  build:
    description: 'Yarn build'
    steps:
    - attach_workspace:
        at: ./
    - run:
        name: Yarn build
        command: yarn build

  docker_build:
    description: 'Docker build'
    steps:
    - setup_remote_docker:
        version: 19.03.13
        docker_layer_caching: false
    - run:
        name: Docker login and setup
        command: |
          # Set BASH_ENV
          echo 'export DOCKER_BUILDKIT=1' >> $BASH_ENV
          echo 'export REGISTORY_URL=${DOCKER_USER}/${SYSTEM}' >> $BASH_ENV
          # echo 'export IMAGE_TAG=latest' >> $ BASH_ENV
          echo 'export IMAGE_TAG=${CIRCLE_SHA1}' >> $ BASH_ENV
          # Login
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
    - run:
        name: Docker build
        command: |
          # Build main
          docker build -t ${REGISTORY_URL}:${CIRCLE_SHA1} --cache-from=${REGISTORY_URL}:build-env --build-arg BUILDKIT_INLINE_CACHE=1  . -f ./docker/Dockerfile
          # Build build-env in parallel
          docker build -t ${REGISTORY_URL}:build-env --target build-env --cache-from ${REGISTORY_URL}:build-env --build-arg BUILDKIT_INLINE_CACHE=1  . -f ./docker/Dockerfile &
          wait
    - run:
        name: Docker push
        command: |
          # Push all in parallel
          docker push ${REGISTORY_URL}:${CIRCLE_SHA1} &
          docker push ${REGISTORY_URL}:build-env &
          wait

  git_diff:
    description: 'Git diff'
    steps:
    - checkout
    # - run:
    #     name: Setup CIRCLE_COMPARE_URL
    #     command: |
    #       echo 'export CIRCLE_COMPARE_URL=<< pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<< pipeline.git.revision>>' >> $BASH_ENV
    # - run:
    #     name: Setup COMPARE_IDS
    #     command: |
    #       echo 'export COMPARE_IDS=${CIRCLE_COMPARE_URL}##*/' >> $BASH_ENV
    # - run:
    #     name: Compare
    #     command: |
    #       echo ${CIRCLE_COMPARE_URL}
    #       echo ${CIRCLE_IDS}
    #       diff=`git diff --name-only ${COMPARE_IDS}`
    #       echo ${diff}
    - run:
        name: Setup
        command: |
          echo 'export PATH=$PATH:${CIRCLE_WORKING_DIRECTORY}/scripts' >> $BASH_ENV
    - run:
        name: git diff
        command: |
          if is_changed "apl/bff"; then
            echo "apl/bffに変更があったよ"
          else
            echo "apl/bffに変更はなかったよ"
          fi
          if is_changed "apl/fe"; then
            echo "apl/feに変更があったよ"
          else
            echo "apl/feに変更はなかったよ"
          fi
          if is_changed "apl/be"; then
            echo "apl/beに変更があったよ"
          else
            echo "apl/beに変更はなかったよ"
          fi
          if is_changed ".circleci/config.yml"; then
            echo ".circleci/config.ymlに変更があったよ"
          else
            echo ".circleci/config.ymlに変更はなかったよ"
          fi

jobs:
  fe_install_deps:
    executor:
      name: fe_default
    steps:
    - sparse_checkout
    - fe_install_deps
    # - install_deps:
    #     system: "fe-web"

  bff_install_deps:
    executor:
      name: bff_default
    steps:
    - sparse_checkout
    - bff_install_deps
    # - install_deps:
    #     system: "bff-ap"

  be_install_deps:
    executor:
      name: be_default
    steps:
    - sparse_checkout
    - be_install_deps
    # - install_deps:
    #     system: "be-ap"

  lint:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    steps:
    - sparse_checkout
    - eslint

  build:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    steps:
    - sparse_checkout
    - build

  build_image:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    steps:
    - sparse_checkout
    - docker_build

  notify:
    docker:
    - image: cimg/node:12.20
    steps:
    - run: echo "notify slack."
    - slack/notify:
        event: fail
        template: basic_fail_1
    - slack/notify:
        event: pass
        template: success_tagged_deploy_1

  git_diff:
    docker:
    - image: cimg/node:12.20
    steps:
    - git_diff

workflows:
  # fe_main:
  #   jobs:
  #   - fe_install_deps
  #   - lint:
  #       e: fe_default
  #       requires:
  #       - fe_install_deps
  #   - build:
  #       e: fe_default
  #       requires:
  #       - fe_install_deps
  #   - build_image:
  #       e: fe_default
  #       requires:
  #       - fe_install_deps
  #       context: DOCKER_HUB
  #   - notify:
  #       requires:
  #       - lint
  #       - build
  #       - build_image
  #       context: SLACK_INTEGRATION

  # bff_main:
  #   jobs:
  #   - bff_install_deps
  #   - lint:
  #       e: bff_default
  #       requires:
  #       - bff_install_deps
  #   - build:
  #       e: bff_default
  #       requires:
  #       - bff_install_deps
  #   - build_image:
  #       e: bff_default
  #       requires:
  #       - bff_install_deps
  #       context: DOCKER_HUB
  #   - notify:
  #       requires:
  #       - lint
  #       - build
  #       - build_image
  #       context: SLACK_INTEGRATION

  # be_main:
  #   jobs:
  #   - be_install_deps
  #   - lint:
  #       e: be_default
  #       requires:
  #       - be_install_deps
  #   - build:
  #       e: be_default
  #       requires:
  #       - be_install_deps
  #   - build_image:
  #       e: be_default
  #       requires:
  #       - be_install_deps
  #       context: DOCKER_HUB
  #   - notify:
  #       requires:
  #       - lint
  #       - build
  #       - build_image
  #       context: SLACK_INTEGRATION

  test_main:
    jobs:
    - git_diff:
        e: fe_default
