#################################
# Service (DB Server)
#################################
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: dummy
  labels:
    app: db-svc
spec:
  ports:
  - name: db-port
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: db
