#################################
# Kustomization (overlays)
#################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/db
- ../../base/cache
- ./namespace.yml
- ./db/config-map.yml
- ./db/sealed-secret.yml

namespace: ext-a
