#################################
# Deployment (FE Web Server)
#################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-web
  namespace: lra-local
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe-web
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      name: fe-web
      labels:
        app: fe-web
    spec:
      volumes:
        - name: contents-vol
          emptyDir: {}
        - name: nginx-conf-vol
          configMap:
            name: fe-web-config
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: default.conf
                path: conf.d/default.conf
      containers:
        - name: fe-web
          image: nginx:1.18-alpine
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 150m
              memory: 150Mi
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: fe-web-config
          ports:
            - containerPort: 8001
          readinessProbe:
            httpGet:
              path: /index.html
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            exec:
              command: ["ls","/usr/share/nginx/html/50x.html"]
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: contents-vol
              readOnly: true
            - mountPath: /etc/nginx
              readOnly: true
              name: nginx-conf-vol
        - name: fe-contents-cloner
          image: t3goto/contents-cloner:0.1
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 50Mi
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: fe-contents-cloner-config
          volumeMounts:
            - mountPath: /apl/fe/dist
              name: contents-vol
