#################################
# ConfigMap (BE Application Server)
#################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: be-ap-config
  namespace: lra-local
data:
  NODE_ENV: production
  GRPC_SV_PAKAGE: rpc
  GRPC_SV_HOST: "0.0.0.0"
  GRPC_SV_PORT: "9011"
  GRPC_SV_PROTOS: geocoding.proto,restaurants.proto,users.proto
  GRPC_CL_GEOCODING_PAKAGE: rpc
  GRPC_CL_GEOCODING_HOST: be-ap-svc.lra-local.svc.cluster.local
  GRPC_CL_GEOCODING_PORT: "9011"
  GRPC_CL_GEOCODING_PROTOS: geocoding.proto
  GRPC_CL_RESTAURANTS_PAKAGE: rpc
  GRPC_CL_RESTAURANTS_HOST: be-ap-svc.lra-local.svc.cluster.local
  GRPC_CL_RESTAURANTS_PORT: "9011"
  GRPC_CL_RESTAURANTS_PROTOS: restaurants.proto
  GRPC_CL_USERS_PAKAGE: rpc
  GRPC_CL_USERS_HOST: be-ap-svc.lra-local.svc.cluster.local
  GRPC_CL_USERS_PORT: "9011"
  GRPC_CL_USERS_PROTOS: users.proto
  DB_TYPE: mysql
  DB_HOST: db-svc.external-service.svc.cluster.local
  DB_PORT: "3306"
  DB_DATABASE: lradb
  REDIS_HOST: cache-svc.external-service.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_TTL: "1000"
  HTTP_TIMEOUT: "5000"
  HTTP_MAX_REDIRECTS: "5"
  HTTP_URL_GNAVI: https://api.gnavi.co.jp/RestSearchAPI/v3/
  HTTP_URL_GOOGLE_GEOCODING: https://maps.googleapis.com/maps/api/geocode/json
  JWT_EXPIRES_IN: "3600"
---
#################################
# ConfigMap (BFF Application Server)
#################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: bff-ap-config
  namespace: lra-local
data:
  NODE_ENV: production
  HTTP_SV_PORT: "9001"
  GRPC_CL_GEOCODING_PAKAGE: rpc
  GRPC_CL_GEOCODING_HOST: be-ap-svc.lra-local.svc.cluster.local
  GRPC_CL_GEOCODING_PORT: "9011"
  GRPC_CL_GEOCODING_PROTOS: geocoding.proto
  GRPC_CL_RESTAURANTS_PAKAGE: rpc
  GRPC_CL_RESTAURANTS_HOST: be-ap-svc.lra-local.svc.cluster.local
  GRPC_CL_RESTAURANTS_PORT: "9011"
  GRPC_CL_RESTAURANTS_PROTOS: restaurants.proto
  GRPC_CL_USERS_PAKAGE: rpc
  GRPC_CL_USERS_HOST: be-ap-svc.lra-local.svc.cluster.local
  GRPC_CL_USERS_PORT: "9011"
  GRPC_CL_USERS_PROTOS: users.proto
  DB_TYPE: mysql
  DB_HOST: db-svc.external-service.svc.cluster.local
  DB_PORT: "3306"
  DB_DATABASE: lradb
  REDIS_HOST: cache-svc.external-service.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_TTL: "1000"
  HTTP_TIMEOUT: "5000"
  HTTP_MAX_REDIRECTS: "5"
  JWT_EXPIRES_IN: "3600"
---
#################################
# ConfigMap (FE Web Server)
#################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: fe-web-config
  namespace: lra-local
data:
  nginx.conf: |
    # uesr
    user nginx;

    # worker
    worker_processes auto;
    worker_rlimit_nofile 100000;

    # pid
    pid /var/run/nginx.pid;

    # events
    events {
        worker_connections 2048;
        multi_accept on;
        use epoll;
    }

    # http server
    http {
      # security (server info)
      server_tokens off;

      # security (connection)
      limit_conn_zone $binary_remote_addr zone=addr:5m;
      limit_conn addr 100;

      # performance
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;

      # performance (timeout)
      keepalive_timeout 10;
      client_header_timeout 10;
      client_body_timeout 10;
      reset_timedout_connection on;
      send_timeout 10;

      # performance (open_file_cache)
      open_file_cache max=100000 inactive=20s;
      open_file_cache_valid 30s;
      open_file_cache_min_uses 2;
      open_file_cache_errors on;

      # performance (compression)
      gzip on;
      gzip_static on;
      gzip_http_version 1.0;
      gzip_disable "msie6";
      gzip_proxied any;
      gzip_min_length 1024;
      gzip_comp_level 6;
      gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;


      # proxy headers
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # log
      log_not_found on;
      error_log /var/log/nginx/error.log error;
      log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                                '$status $body_bytes_sent "$http_referer" '
                                '"$http_user_agent" "$http_x_forwarded_for"';
      access_log /var/log/nginx/access.log main;

      # cache (no cache)
      expires epoch;

      # mime types
      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      # virtual server
      include /etc/nginx/conf.d/*.conf;
    }
  default.conf: |
    # vertual server (default)
    server {
      listen 8001 default;
      listen [::]:8001;
      server_name localhost;

      # root
      root /usr/share/nginx/html;
      index index.html index.htm;

      # location (static)
      location / {
        try_files $uri $uri/ =404;
      }

      # error page
      error_page 500 502 503 504 /50x.html;
      location = /50x.html {
        root /usr/share/nginx/html;
      }
    }
---
#################################
# ConfigMap (FE Contents Cloner)
#################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: fe-contents-cloner-config
  namespace: lra-local
data:
  CONTENTS_SOURCE_URL: https://github.com/t3-goto/lra-app
  CONTENTS_SOURCE_BRANCH: develop
  CONTENTS_SOURCE_DIR: apl/fe/dist
