#################################
# ResourceQuota（application）
#################################
# apiVersion: v1
# kind: ResourceQuota
# metadata:
#   name: quota
#   namespace: lra-local
# spec:
#   hard:
#     requests.cpu: "32"
#     requests.memory: "64Gi"
#     limits.cpu: "32"
#     limits.memory: "64Gi"
# ---
#################################
# ResourceQuota（system）
#################################
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: lra-sys-local
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: "1Gi"
    limits.cpu: "0.5"
    limits.memory: "1Gi"
