apiVersion: v1
data:
  DB_DATABASE: lradb
  DB_HOST: lradb.cs7qvmefeas0.ap-northeast-1.rds.amazonaws.com
  DB_PORT: "3306"
  DB_TYPE: mysql
  GRPC_CL_GEOCODING_HOST: be-ap-svc.app-a.svc.cluster.local
  GRPC_CL_GEOCODING_PAKAGE: rpc
  GRPC_CL_GEOCODING_PORT: "9011"
  GRPC_CL_GEOCODING_PROTOS: geocoding.proto
  GRPC_CL_RESTAURANTS_HOST: be-ap-svc.app-a.svc.cluster.local
  GRPC_CL_RESTAURANTS_PAKAGE: rpc
  GRPC_CL_RESTAURANTS_PORT: "9011"
  GRPC_CL_RESTAURANTS_PROTOS: restaurants.proto
  GRPC_CL_USERS_HOST: be-ap-svc.app-a.svc.cluster.local
  GRPC_CL_USERS_PAKAGE: rpc
  GRPC_CL_USERS_PORT: "9011"
  GRPC_CL_USERS_PROTOS: users.proto
  GRPC_SV_HOST: 0.0.0.0
  GRPC_SV_PAKAGE: rpc
  GRPC_SV_PORT: "9011"
  GRPC_SV_PROTOS: geocoding.proto,restaurants.proto,users.proto
  HTTP_MAX_REDIRECTS: "5"
  HTTP_TIMEOUT: "5000"
  HTTP_URL_GNAVI: https://api.gnavi.co.jp/RestSearchAPI/v3/
  HTTP_URL_GOOGLE_GEOCODING: https://maps.googleapis.com/maps/api/geocode/json
  JWT_EXPIRES_IN: "3600"
  NODE_ENV: production
  REDIS_HOST: cache-svc.ext-a.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_TTL: "1000"
kind: ConfigMap
metadata:
  name: be-ap-config
  namespace: app-a
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: be-ap-svc
  name: be-ap-svc
  namespace: app-a
spec:
  ports:
  - name: be-ap-port
    port: 9011
    protocol: TCP
    targetPort: 9011
  selector:
    app: be-ap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-ap
  namespace: app-a
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: be-ap
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: be-ap
      name: be-ap
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: be-ap-config
        - secretRef:
            name: be-ap-secret
        image: t3goto/be-ap:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls
            - /usr/local/bin/node
          failureThreshold: 10
          initialDelaySeconds: 0
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: be-ap
        ports:
        - containerPort: 9011
        readinessProbe:
          failureThreshold: 10
          initialDelaySeconds: 0
          periodSeconds: 15
          successThreshold: 1
          tcpSocket:
            port: 9011
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 150m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 100Mi
        startupProbe:
          failureThreshold: 100
          initialDelaySeconds: 0
          periodSeconds: 3
          successThreshold: 1
          tcpSocket:
            port: 9011
          timeoutSeconds: 1
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: be-ap-secret
  namespace: app-a
spec:
  encryptedData:
    ACCESS_KEY_GNAVI: AgCDLCT2RScqyTJW4rgE+VTOv7hrJuiJ3O5EDgcU3/BsT4TncMox5tmL4ikhxSlMrUNF4sb73mqXjAIxHyqzhfNLdulb8DrNoQ/V2rSrp/cs7ypy51taxRjCn1iiuSb9F73RnvH6RJP64JTKTvevL7pKiUm1+9J1YV++TOuzQ0mlqaFRk5t2cN0MbYpv5FHsm5jA4mNXd5WHPCxQaNGEqdaNAuos3RcZ/dd6aJBy8txiBqNG7mzAXruTUNwHJjxwJ4RFynA0D3jSxiDfRhBXGTyZHQ4a9YIvCJBmplpTmOZKQNA3GQ8c0RS/UjUOM2QvbyKs2tIO0OMbT8Lqit9t6INJEBP/Cr9Kgcae1Rs/NmrGDdLa+kTJKANu96FMNa5uO29E7f0+8HTShiTnZoMAVSxrqxBDl4cLRGKLT/gm+2bR/ENDjaQjgREvUnGWZgBQkNEN6X17OINWNf20oGhWrgAkCObzIbKBYs1QAwmxzkMe5FFmgQrYAZOdT2TcLZfKokrg+29WgliIELqDG68U8SvHZqQyNeYs18K3kqxD2/w9MHrWGXqQP0G2lNE6cJ5ja7rlxUlc1zrtOB9/XgXqr9NKZFzjJkv/ybuNhzs3iKgJiYy9hpnUVDTUrtdvYTOx6eK883veliC7lqZie4PtIPlvg9wfTckapx+KAzA2M8tRASM7/4Co6EwGWSpR0B+zMob3TQA3XK7K+YeJK/dzPDcWpgqYJ0InQ/USHAMmXttfqQ==
    ACCESS_KEY_GOOGLE: AgANKb+bd+8Aq2YmeYHBCjsj6PJq4/Hi4z8uftzpNARHZBU/Rw9HHtwO7Q4PFafTKT13mdE//yydLoROCpNqtVfmiGBwA7OPf83/PbLbcT6MAY17GQ1FHzcmRGScWcWwLhMDGrPJk+q7qQuC+nO5I9ueQrMMe7DfCt8Pi9JJQRbs2aTPIocG/UQD6OsnjXQ5fZgKyXmKTziqL9r8i++Fselxo/FPcWLWoS3XvL8dd2liqcKMgt30qePJCru6IYPaQ3tIf3fZTVHB2iyQqOc0wAFG8YnqYNRctxYWwnnZNr4DqhuLeq70c/N1avf4v2wv10iWOIiUB8BO/mw21Zj1rk96U5BBOgam8mSu07Tw9y5oRTsAnR225g09W93BXSI8gRzPakzv2Xj/fxKRFVFMdrlaZG0x2+vZcWQAT9ZnkQzjv/TKmLAUmfMFKS04s51NEkTvB4uRTxL9qsJ8BZbm1V1zExme8VHrJfMRhA3PJ4bpM3WiIJpRs5WHZV91NB3J19ctWg+Db4fslNg1uTl/RRDYyUzNCr2Smb8ogwuCePUuyBkP56eb1wUwacodYN916wLgvnd8gmCJs/yPFgu2hhAimCWwlau5SuMNKRRPLg6BVtQLv1LkbysgaoVzIag86u72UA64d7yJYnrPE38wa0AykXEU8tBOs9wJPEJzi2Zq6Xf8Bjic1BlPsyOwbJbBLKpunUvQRnzKfm1noDhRD/F5kETF04uBDM5ECblKXOqcJCi0kQf1/PA=
    DB_PASSWORD: AgAv5pVCA9MsdIUSDTm4OKO3Q+XN4HJWgJdn9p9TiwpqvRSJUq9Y0aYFmhXK7cQDmefmw90k8DHGiyZxh5IM8hfRuG/BLVYEHnxZocP+LsW5wKDRu8EA1GRIP+tBIx6/Y9OC/AFDDVCKsfw/vTf/z/skNZENMAanjTUxbI/UsHZ6MVJgpBYOMzaI+OhkTOKdZLafC4s23Y+RizG53Z9fw+oCnsyOrY2V4w1rjLliqYccK1MTbHVTXvuv3pmnqFL76Q332EAOnnyNATPP0YUUSnNwwnW0UubBLmoVIgAzBa8lXbem+aAakxUTuEk62aghM/5SozvsZw8DBFum5ujaeXOLTErF19I9eK1BeudUK+qc9qDce9PuVPK0ywXGDp3vMd7Gu+QoG0Nh5W6lH4F92hGgJ9YvYQw5ctXMPi5/VsMKPQYNYs2IpEqi8O63smKdyIsehFeq0dVUyBarRzmxfL0NIO+fSX3I1xavfGoEK21gPfQ3R8S/JOT2FZ6yKEGzsYl1di5jPzVt8UmgQ0WHD9LllTh0RrwARb9lFmGytWR1PMQiIS0rFlh3xE1vvORT8DvMoitcCdsttnZXYPyCNDekLY5L8Sn78+SM0kCXSfcu8hFgaRy/y+hU8tjuoEXFF2GY3UsW9PKv6LhavEcPswCQl2u7N8ETlnH+5c9Tdlbhrcg5NTshmVqI7Po270cMo5b5rYVWCga6P2Fn6jpoEHSC
    DB_USERNAME: AgA/bDVI2w9PhJVYi164SN+qYI1KVxdgiGqPKViIgIN0FpX2JJcBsrYxdzkAkcrb/lsAZA0nTnr9QyE+bKst9e5E6tPD3gb8isVCANC8tg5EfX8hQc3ehDM21NgjpW4lAtEN41YLW8E+wOgwRVrfvWQ6I8M5VXnDCliFulXnGBeiykDCw+xTu1dsxLO7ZSwvkkiSgif9o5PAYZ2PGeZdgZdvPG2WHVR+O9ERVQG23i3Bc+9RKke+tSqaALPPBdGCWzDKi6HBM05gvEIHiPSXK0kiE7MQxN25bns/JdsWjQpkqGRoCugVYekfzfSvCwYFZoAcoQOi77dLwRAbLB5hsKoBXjf2K7/haZKMSiyAuoRylJ8V0KLs0CAs1GyNC2u/baaln5clWwiBTshN4dvcmIsGsu6PPjqZMOFjFIQvqR7+mYeOkxRH7Kqdzcz1fi+sC2xr1Goew6/8jjH+UmMb71ucTulu0rzRHtrlg0Q4P0a2b3WCg8Gq6i6gzI4s8qt9KfcMZ6hicwcrsGKU/uqwLpZUCF7VdmoNoo+vT24WsgOGmoo9i1GJCNFcE2ahOYCiVG5PWf1pN/9Pe+WQ0tdx3OSV2eRxepypxUCp5p8azXdYKQMrM1fhQ0YGcXcSiwLU6993HPM83wMhhwieXCNixnCtl1X19AU7lSIaiLgZjMiWEAA1enuNcnEe5oQT/skpjK6w2moQpP8=
    JWT_SECRET: AgAPvFHhDSJIFRzhCxkvuhCp40dorK8EVw47/Soy0M2fQh3MoI+e2bBbUQ6xnYL/Vg2MYS4eeqSB0tEW3EAaM9qwj3DRb8xgmp6H/66l9oe+QitFxO9H7qdXMGanzwpDTblPd5HHobGdOIpe6A4lt+na7jQ26+MxWqBxw2hDmdL+eHIHDSVxR45dxZGyDJajeAroVaZP4p7Jj9dxwsicWKpqXaA6nnUdabSzyqIUxlsTXSEcuRPPEC9X4ivHN0E78Cqyf3KxyhCWkREK7Kv2UWWLW+TeO/w41GD3dKJhAC7ToX2UNXnTTEpmCQkZXLS0ohUaqhNw1sy6YsPlZ3xV+HcVPSBig3zwAjYqu57+w6mmc2dBUusiryR0N7TCT/lpr1fa7lSXefWU8YDaksZO78W4QLconU1Lc+iea3n7Vd72M7g56XRg0CY9tAXxcGrGJaIjA3ERrNSh4Ml6L5cK62d50HMU7y3PoSVsk28fGbd4fnhEFDn10E19ywMK9G+48cPwn5pxGPTa/5tbvClSyS537HxfPmnP2w/Gyx7SIwNrjbNnasb7oPYWUEGsutmjU2sN8oniGGquoNqiOOUYpeAVbabrIR6OBs0UMU4To1DSmFG9hB8WJTlXERFQCIStj0Y/03Y126GL//5peeqZJw5Z8x8+mgwrMVtxOuJU5hz6qe/cG5ZM0bRxYjs2g2E52gBf+dpGBJSdRtL11Y4VCJal
  template:
    metadata:
      creationTimestamp: null
      name: be-ap-secret
      namespace: app-a
    type: Opaque
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: be-ap-dr
  namespace: app-a
spec:
  host: be-ap-svc.app-a.svc.cluster.local
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: be-ap-vs-mesh
  namespace: app-a
spec:
  hosts:
  - be-ap-svc.app-a.svc.cluster.local
  http:
  - route:
    - destination:
        host: be-ap-svc.app-a.svc.cluster.local
        port:
          number: 9011
