#################################
# Deployment (BE Application Server)
#################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-ap
  namespace: dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-ap
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      name: be-ap
      labels:
        app: be-ap
    spec:
      containers:
        - name: be-ap
          image: t3goto/be-ap:latest
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 150m
              memory: 150Mi
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: be-ap-config
          - secretRef:
              name: be-ap-secret
          ports:
            - containerPort: 9011
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9011"]
            initialDelaySeconds: 0
            periodSeconds: 15
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            exec:
              command: ["ls","/usr/local/bin/node"]
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
          startupProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9011"]
            initialDelaySeconds: 0
            periodSeconds: 3
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 100
