#################################
# IstioOperator (default)
#################################
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: dummy
  name: istiocontrolplane
spec:
  profile: default
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:ap-northeast-1:787350286285:certificate/979b41a4-88f4-4d51-944c-42d453a88fcf"
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443,15443"
            service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
