#################################
# Kustomization (overlays)
#################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ./namespace.yml

namespace: istio-system


patchesStrategicMerge:
- istio-operator-patch.yml
- ingress-gateway-patch.yml
