#################################
# Kustomization (overlays)
#################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ./namespace.yml
- ./sealed-secret.yml

namespace: istio-system

patchesStrategicMerge:
- ingress-gateway-patch.yml
