#################################
# ConfigMap (DB)
#################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: lra-local
data:
  MYSQL_DATABASE: lradb
  TZ: Asia/Tokyo
---
#################################
# ConfigMap (BE)
#################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: be-config
  namespace: lra-local
data:
  NODE_ENV: production
  GRPC_SV_PAKAGE: rpc
  GRPC_SV_HOST: "0.0.0.0"
  GRPC_SV_PORT: "9011"
  GRPC_SV_PROTOS: geocoding.proto,restaurants.proto,users.proto
  GRPC_CL_GEOCODING_PAKAGE: rpc
  GRPC_CL_GEOCODING_HOST: be-server
  GRPC_CL_GEOCODING_PORT: "9011"
  GRPC_CL_GEOCODING_PROTOS: geocoding.proto
  GRPC_CL_RESTAURANTS_PAKAGE: rpc
  GRPC_CL_RESTAURANTS_HOST: be-server
  GRPC_CL_RESTAURANTS_PORT: "9011"
  GRPC_CL_RESTAURANTS_PROTOS: restaurants.proto
  GRPC_CL_USERS_PAKAGE: rpc
  GRPC_CL_USERS_HOST: be-server
  GRPC_CL_USERS_PORT: "9011"
  GRPC_CL_USERS_PROTOS: users.proto
  DB_TYPE: mysql
  DB_HOST: db
  DB_PORT: "3306"
  DB_DATABASE: lradb
  REDIS_HOST: cache
  REDIS_PORT: "6379"
  REDIS_TTL: "1000"
  HTTP_TIMEOUT: "5000"
  HTTP_MAX_REDIRECTS: "5"
  HTTP_URL_GNAVI: https://api.gnavi.co.jp/RestSearchAPI/v3/
  HTTP_URL_GOOGLE_GEOCODING: https://maps.googleapis.com/maps/api/geocode/json
  JWT_EXPIRES_IN: "3600"
---
#################################
# ConfigMap (BFF)
#################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: bff-config
  namespace: lra-local
data:
  NODE_ENV: production
  HTTP_SV_PORT: "9001"
  GRPC_CL_GEOCODING_PAKAGE: rpc
  GRPC_CL_GEOCODING_HOST: be-server
  GRPC_CL_GEOCODING_PORT: "9011"
  GRPC_CL_GEOCODING_PROTOS: geocoding.proto
  GRPC_CL_RESTAURANTS_PAKAGE: rpc
  GRPC_CL_RESTAURANTS_HOST: be-server
  GRPC_CL_RESTAURANTS_PORT: "9011"
  GRPC_CL_RESTAURANTS_PROTOS: restaurants.proto
  GRPC_CL_USERS_PAKAGE: rpc
  GRPC_CL_USERS_HOST: be-server
  GRPC_CL_USERS_PORT: "9011"
  GRPC_CL_USERS_PROTOS: users.proto
  DB_TYPE: mysql
  DB_HOST: db
  DB_PORT: "3306"
  DB_DATABASE: lradb
  REDIS_HOST: cache
  REDIS_PORT: "6379"
  REDIS_TTL: "1000"
  HTTP_TIMEOUT: "5000"
  HTTP_MAX_REDIRECTS: "5"
  JWT_EXPIRES_IN: "3600"
---
#################################
# ConfigMap (FE)
#################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: fe-config
  namespace: lra-local
data:
  NODE_ENV: production
  BFF_BASE_URL: http://lratg.com/api/v1
---
#################################
# ConfigMap (FE ContentsCloner)
#################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: fe-contents-cloner-config
  namespace: lra-local
data:
  CONTENTS_SOURCE_URL: https://github.com/t3-goto/lra-app
  CONTENTS_SOURCE_BRANCH: develop
  CONTENTS_SOURCE_DIR: apl/fe/dist

