apiVersion: v1
data:
  DB_DATABASE: lradb
  DB_HOST: lradb.vpc.internal
  DB_PORT: "3306"
  DB_TYPE: mysql
  GRPC_CL_GEOCODING_HOST: be-ap-svc.app-a.svc.cluster.local
  GRPC_CL_GEOCODING_PAKAGE: rpc
  GRPC_CL_GEOCODING_PORT: "9011"
  GRPC_CL_GEOCODING_PROTOS: geocoding.proto
  GRPC_CL_RESTAURANTS_HOST: be-ap-svc.app-a.svc.cluster.local
  GRPC_CL_RESTAURANTS_PAKAGE: rpc
  GRPC_CL_RESTAURANTS_PORT: "9011"
  GRPC_CL_RESTAURANTS_PROTOS: restaurants.proto
  GRPC_CL_USERS_HOST: be-ap-svc.app-a.svc.cluster.local
  GRPC_CL_USERS_PAKAGE: rpc
  GRPC_CL_USERS_PORT: "9011"
  GRPC_CL_USERS_PROTOS: users.proto
  GRPC_SV_HOST: 0.0.0.0
  GRPC_SV_PAKAGES: rpc,grpc.health.v1
  GRPC_SV_PORT: "9011"
  GRPC_SV_PROTOS: geocoding.proto,restaurants.proto,users.proto,health.proto
  HTTP_MAX_REDIRECTS: "5"
  HTTP_TIMEOUT: "5000"
  HTTP_URL_GNAVI: https://api.gnavi.co.jp/RestSearchAPI/v3/
  HTTP_URL_GOOGLE_GEOCODING: https://maps.googleapis.com/maps/api/geocode/json
  JWT_EXPIRES_IN: "3600"
  NODE_ENV: production
  REDIS_HOST: cache-svc.ext-a.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_TTL: "1000"
kind: ConfigMap
metadata:
  name: be-ap-config
  namespace: app-a
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: be-ap-svc
  name: be-ap-svc
  namespace: app-a
spec:
  ports:
  - name: be-ap-port
    port: 9011
    protocol: TCP
    targetPort: 9011
  selector:
    app: be-ap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-ap
  namespace: app-a
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: be-ap
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: be-ap
      name: be-ap
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: be-ap-config
        - secretRef:
            name: be-ap-secret
        image: t3goto/be-ap:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls
            - /usr/local/bin/node
          failureThreshold: 10
          initialDelaySeconds: 0
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: be-ap
        ports:
        - containerPort: 9011
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:9011
          failureThreshold: 10
          initialDelaySeconds: 0
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 150m
            memory: 150Mi
          requests:
            cpu: 10m
            memory: 10Mi
        startupProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:9011
          failureThreshold: 100
          initialDelaySeconds: 0
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: be-ap-secret
  namespace: app-a
spec:
  encryptedData:
    ACCESS_KEY_GNAVI: AgA+zwjP4fu/loJBPQN+fnhsw/dA67PXwoB/uS17WT12IEUGyqApE/vPlD0wXZkCYEdWq4mnmqku3618EAGNPJMRuZ6JGhbL4WPOljMRKKrGths0nG8VEjOg/VL+HfYBmN3uA0sPMJLSSSxU4pHioCschxeG2sFK81dgc9MaxFQ1KD7x88C/wAMge84Fe+i8jH8BkE5n8Q1tia2GFUHisbJ1V7Q3341h+sROGNZEDnyUE0/fELgYCtTjjqLiJrIFeOpTRLyCdEBcXAjDGC1dpyIVEkRRN+hA1iJxfK+MFwU1q7/Ih0yoRVuJFsYxRLIaqx2OC2wecmKg5f0/LXIdPV0dc5tWJO5Zi6Qhq1PTg7xVLvYIX577mPmVw12V3y8A8erbS6j/AWdxmpM8qA18i9oAW8Lt8BUgTNwph4u5OUbG13RC1davL/6fxAhUKmxqTG111gCbGt1JwjC/jBnJthVZHNSdT7HtpNVK8cUB1aYtK946KBqrHdwxLCSkXk7Kk9CmpEq/RlTErJi6bcxxPqP7Lypf9wUw1s6W4HZRekYOyEM7ab2luwAmkRUGVEczuDJNDUQCi44yMNbf8TzccIMSA0IRZGySf3yjn43tGgQfgPtiBoF2gDqRZFthfeDwMahi3J+uU9MkNmOomCIIEVZfYRdzCRlV644ADuFWhJCMqkMYl+IagnXSJYKlay8iVr9o++kPgRBzJI1ku1caukfL8MxYF9DSD4hPhUZ5Y/gFbA==
    ACCESS_KEY_GOOGLE: AgCdoTb0kPa0B0rYOgpeCde/Ygo0xSIfS/l5D/fJfqU0EIYMNaUi4LgV/BhARlRMuJ8Z9Dq7tPDBk9y6eyOTKitimiECHuXAeCyfL/yMdd8osr2GEqpXpopzkDstveiFx0wWe33w6XVHiMl0vCNDwJBWz7hE6p2WQhSZ8DKTrQLzHgFk+VW7fDlvZn802dViwrQNB0U70BlXVHjgJHhqBBVhCs6oHf3jKmxopiYJOh6SGOeLIjeNgmkoJr5XBk8gpSme0XLUXkVN6JU3TeY3A2jqI3HGp3UJ5Znhr2Jk7NKnRx58RwmVnOaBpEaVNGts2udNmZXgIhZtw4vDVDTGkqAzzUhzXmk7ncEYEd5jPWFjlARjDnfk8U76OvXaJ+9QQK1z95NxCBO0VQmQJ965/u8wmHI530SYqzVuqMRqSbNykGvjUZItDn8PPpnL4CUl/JXvN2AZvdaiE4zbJs9DHPd7ldn/prHJvQT84YNusFl6pNJoJMsd64pa//gnP/ooeJ5+a2cYhG2gtDldzW77vi3xYKAfZtRRu2cWO+2DGt8lCCtJU3CgVub8gSO8rd2XqUeoCZklRlFVK3xHKq1WeYZws/U/MZj7RVanR9UQvJxTubHVaHjHni0glYRjOQkPj9cEmG3Z9IsIpUYkhxT9bzOZ9BchgZKC5VEi7CDCf7yyyt/493pv9K7250OUdkIgMJ71uCoHUn+83uaKxInTWpMGp7oOdK3hgODBKTgCiPdyCJD2YMKpZlE=
    DB_PASSWORD: AgANWvGojzxjVB/9G9LYndIs5ZPeSHSflZPJYJiKSCtcTYRF5ugYoM7IBknK3JHDtV669fWhHtH4R1Km7vrZfS2MyXl99ZTQl9F86QpkC2LfKACiC3CFeK/IJhhLc6zRFEPcRR84V12Dq1ARlzUhz99S94HapJQoxZ6axAPlWd9D8d4p5hWV8808R3YIChKUhJKsDaTWdJh+ZDgxu+jlFq6ODO/+dkm+j9LXJtQmOAqTuBfnDX6zRXkmOXpZVfY0IaVNVQOPoXqiE3pqBxPm9Y6RC2Zh5XutTJ6RBm5CbXy565oKkbJlsF0rC8OMFRgQfFHvzam9v/2ZrpkFLzoMAWO4Tl/19RluuzSOBkGPDqvUPEMhhKe9TDL6/C1jI5ut4Bndpk8Y1/AYsFRL0qHeAuDGPBfNZn/uQbLrWovwqOq5XzaKVTNrAuEtSkA2Dc/azOZx7Sar9wkEwyPWVhJKl2hO3zxYpRxJX2aiEJtSFOfdcppe7B2glGx4lauoOKpsSM6LZa78wsNKF1pm75G1PdZ5XKaYoU04WJ51AVIxhpjk3xRAkTUNojNYbd6XnqK9cf3sWzHXaV8n0cwL8EsBHYpYTbgsPIMYIyiWJtEbEl/5c1EASnoTfXKX4xUzrjMGdnitjFrKbu6CLE1RMDGvuWO9cjF+cV+WLIL/Rc4Rk+EJWcby5ozQ87bdU1sCG7Wvua0v56nYghSpFQ==
    DB_USERNAME: AgAiqILbk7uaROUKpw2vwX1kPi51XBY0dTutIy9IdKA8BYju49xCwLvu3lv11oaBtQ1c6s2+OFqt+gc6nfwZwRw8rPjtsO263aNdB1F5Eyb/QIZ9f2VUdABCh/CUekIg9I6ozntmDL3N7+QRHQ7+NWghAqHWl8X7vuj6tludPOGbt3TdznwnqGBgisebsrr14IZW4er7Kirz+CfXBwvDQPalmfp50c5hnbIhl0Y9RHq44YD0eE+FJbnPhJ79Mt8STF2WDAgdAQ70RzLfDPJCTXQugn+MM86APCTEH6yRGsUS9+PYxGQhSjBKLyfxEaj7Qa+9as1d+CYio6vHZUv+zKz7Dmhgle24gTemlSOlzglIpDftfUi5ippVCeFXulXOvlVbQkX6Npo5Pdu0Ed3ZLK4gjmnSB/wOQQgWAVqcvVyUlr7IJidTWaoBbrca+UDfEYmCl58Ld1VTrDeZovnnwaWhEHQWY84JmW5OnP85rdBuCvJz/phwzN31a5rZFpDBHCwpHeEtpB8rZ4dAfplQdU1WP6upQHYdatSaMJvYwUJCLPa6q2fzeYFmMtJkHIyv9wCqhZi0ub60KkA4/clJtN4vY+ns1CypAivZucMpfnDndi23QwR6f5aHBVmy4hyzBZ216xICfPiXUvkFQ0HbGpEWIx3utF/YDaGwsFSUl7dRujN+vqnPR56ebPfFhpu5c9qMAdQPfg==
    JWT_SECRET: AgAMlcmWAbNGOhgPoQ2XRw6FJFMNmZEYz1HTMwr1vBRg35Jz0zwbF9XFRxreWw7Oh2zI6fAjum56feAK3bWBglXEKv76Bf9y5EldWlgaTmN6t4pNk2i8A2HsLHtJMkR/t4clvg8HwmhSThBYkoR0k9uK3ooIiczAo6Nl+XwDKrQujuxZtk7+mmmfsL4MpK5RGUynfnoQOrbHzRKl8N6ae6gn6JR4zGZnBAQ1gzNGgQ+ygFcMaiSLVtvqwqueVIdS/BtrwNcVCsquyaQWpq+tewgmTRW/HF52Eg9lqQ2oNejncOBZzyHai5O774UxbN646wnhbOLZaZm0nRPSV2QofeXiTG1FPhqQwYLmmB7oWgefBlk83ailw4A4oYB9LxIGBHlDWDAbBKaAvl2cgoBn4t3RKzprGsZdoiWoZuwnLH+uVD5RD6NSd91wc0/M6lV8ItsraXSuooGZrasVvI8RQwL8TCKXrPqgWIghtrwdN20AAg5MvGEFVMyHcetheQMeILp8zNcmDxKWgsXKr5SPnDY+JnySVAzfiHTfssk6k2qWkHyEjGskS6rPHssm7Tu1JEjCMLEPidc6S2SnQ8VlBzgACznR9H6pdSecvxW8V9jCe8ZQOTEg17spmZ3GXCf09gsqnELN6yD/6FRUbDmNKUnfFdScZL9s0YoXTiKqg15YX0IXeFjvWht1a5g9olhIyls8/QuwYX85B0RueRtcfGu9
  template:
    metadata:
      creationTimestamp: null
      name: be-ap-secret
      namespace: app-a
    type: Opaque
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: be-ap-dr
  namespace: app-a
spec:
  host: be-ap-svc.app-a.svc.cluster.local
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: be-ap-vs-mesh
  namespace: app-a
spec:
  hosts:
  - be-ap-svc.app-a.svc.cluster.local
  http:
  - route:
    - destination:
        host: be-ap-svc.app-a.svc.cluster.local
        port:
          number: 9011
