#################################
# Deployment (DB Server)
#################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mysql:5
        name: db
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 150m
            memory: 300Mi
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: db-config
        - secretRef:
            name: db-secret
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: local-db-data-v
          mountPath: /var/lib/mysql
        - name: local-db-sql-v
          mountPath: /docker-entrypoint-initdb.d
        - name: local-db-conf-v
          mountPath: /etc/mysql/conf.d/my.cnf
      volumes:
      - name: local-db-data-v
        hostPath:
            path: /run/desktop/mnt/host/c/work/app/lra-pj/lra-app/infra/local/db/data
      - name: local-db-sql-v
        hostPath:
            path: /run/desktop/mnt/host/c/work/app/lra-pj/lra-app/infra/local/db/sql
      - name: local-db-conf-v
        hostPath:
            path: /run/desktop/mnt/host/c/work/app/lra-pj/lra-app/infra/local/db/conf/my.cnf
